---
title: "Police Arrests"
author: "Nic Coxen"
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
knitr::opts_chunk$set(echo = FALSE)
knitr::knit_engines$set(python = reticulate::eng_python)
knitr::opts_chunk$set(python.reticulate = TRUE)
use_python('C:\\PROGRA~1\\Python38\\pythonw.exe')
knitr::opts_chunk$set(message = FALSE)
options("getSymbols.warning4.0"=FALSE)
options(comment = NULL)
library(fpp2)
library(ggfortify)
library(tidyverse)
library(kableExtra)
library(ggthemes)
library(xts)
library(lubridate)
library(hrbrthemes)
library(gridExtra)
library(ggResidpanel)
library(grid)
library(forecast)
library(astsa)
library(readr)
library(TTR)
library(ggpubr)

library(lattice)
library(dplyr)
library(imager)
```

```{r}
arrests <- read.table("https://raw.githubusercontent.com/NicJC/Datasets/main/Arrests.csv", 
                  header = TRUE,
                 sep = ",")

```

```{r}
head(arrests)
```


```{r}
plot(arrests$Year,arrests$Age, xlab = "Year", ylab = "Age" )

```
```{r}
```


```{r}
ggplot(data=arrests,aes(x=Category,y=Year,color=Sex))+ geom_line() + geom_point(size=2)
```
```{r}
boxplot(arrests$Age,horizontal=T,main="Age of Arrested",xlab="Age")
```



